targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/src/models/**.dart
      - test/**.dart
    builders:
      mockito|mockBuilder:
        generate_for:
          - test/**.dart
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      json_serializable:
        options:
          field_rename: snake
          create_to_json: false
          checked: true
