// Mocks generated by Mockito 5.0.13 from annotations
// in flutter_infinite_list/test/post_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_infinite_list/posts/models/post.dart' as _i5;
import 'package:flutter_infinite_list/posts/repository/post_repository.dart'
    as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeClient extends _i1.Fake implements _i2.Client {}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i3.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient()) as _i2.Client);
  @override
  _i4.Future<List<_i5.Post>> fetchPosts([int? startIndex = 0]) =>
      (super.noSuchMethod(Invocation.method(#fetchPosts, [startIndex]),
              returnValue: Future<List<_i5.Post>>.value(<_i5.Post>[]))
          as _i4.Future<List<_i5.Post>>);
  @override
  String toString() => super.toString();
}
