name: weather_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.0.1
  meta_weather_api:
    path: ../meta_weather_api

dev_dependencies:
  build_runner: ^2.1.1
  coverage: ^1.0.3
  json_serializable: ^4.1.4
  mockito: ^5.0.15
  test: ^1.17.11
